"""Playback-backend interface.

Every backend (Lyrion, local browser, DLNA, AirPlay, ...) implements the
`PlayerBackend` Protocol. The `name` field is the backend identifier the
frontend uses to route commands; the per-player `id` is opaque to the rest
of the app (MAC for Lyrion, UDN for DLNA, etc.).
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

import httpx


class BackendError(RuntimeError):
    """Raised when a backend is unreachable or returns an error."""


@runtime_checkable
class PlayerBackend(Protocol):
    name: str

    async def list_players(self, client: httpx.AsyncClient) -> list[dict[str, Any]]: ...
    async def get_status(self, client: httpx.AsyncClient, player_id: str) -> dict[str, Any]: ...
    async def play(self, client: httpx.AsyncClient, player_id: str, url: str) -> dict[str, Any]: ...
    async def add(self, client: httpx.AsyncClient, player_id: str, url: str) -> dict[str, Any]: ...
    async def insert(self, client: httpx.AsyncClient, player_id: str, url: str) -> dict[str, Any]: ...
    async def play_show(self, client: httpx.AsyncClient, player_id: str, urls: list[str]) -> dict[str, Any]: ...
    async def queue_show(self, client: httpx.AsyncClient, player_id: str, urls: list[str]) -> dict[str, Any]: ...
    async def start(self, client: httpx.AsyncClient, player_id: str) -> dict[str, Any]: ...
    async def pause(self, client: httpx.AsyncClient, player_id: str) -> dict[str, Any]: ...
    async def stop(self, client: httpx.AsyncClient, player_id: str) -> dict[str, Any]: ...
    async def next_track(self, client: httpx.AsyncClient, player_id: str) -> dict[str, Any]: ...
    async def prev_track(self, client: httpx.AsyncClient, player_id: str) -> dict[str, Any]: ...
    async def eject(self, client: httpx.AsyncClient, player_id: str) -> dict[str, Any]: ...
    async def set_volume(self, client: httpx.AsyncClient, player_id: str, volume: int) -> dict[str, Any]: ...
    async def seek(self, client: httpx.AsyncClient, player_id: str, delta_seconds: int) -> dict[str, Any]: ...
